### ISSUE TITLE
Always return ResourceNotFoundThe specified resource does not exist. RequestId

### ISSUE THREAD

**Issue by madnik** [dmichael/azure-contrib#1]
I created a shared access resource using the library.

uri = "https://accountname.blob.core.windows.net/mycontainer/image.png"
		signer = Azure::Contrib::Auth::SharedAccessSignature.new(uri, {
  			resource:    'b',
  			permissions: 'w',
  			start:       (Time.now - 5*60).utc.iso8601,
  			expiry:      (Time.now + 30*60).utc.iso8601
		},'accountname')

when I try to put a file named image.png using this it returns ResourceNotFound error. Is the signature not correct.

**Comment by dmichael** [comment]
Is the uri the actual code you are attempting to use - or did you replace "accountname" and "mycontainer" with values? just thought I would clarify ...

**Comment by dmichael** [comment]
In my experience a ResourceNotFound error means that the thing you are looking for does not exist, not necessarily that the signature is not correct. I believe there is another type of "forbidden" error for that

**Comment by madnik** [comment]
The issue is resolved. It was a issue with my rest client doesn't recognized url encoding of signed url.
